version: '3.1'

services: 
  adminer: 
    image: adminer
    ports: 
      - "8090:8080"
    restart: always
  db: 
    image: postgres
    environment: 
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fdBase
    ports: 
      - "5432:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
    db_data: