spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/fdBase
    username: postgres
    password: secret
    driverClassName: org.postgresql.Driver
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false


flyway:
  baseline-on-migrate: true
  locations: classpath:db/migration

endpoints:
  flyway:
    web:
      enabled: true

security:
  clientid: "asdasdasd"
  secret: "asdasdasd"