spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/fdBase
    username: postgres
    password: secret
    driverClassName: org.postgresql.Driver

flyway:
  baseline-on-migrate: true
  locations: classpath:db/migration

endpoints:
  flyway:
    web:
      enabled: true