
ALTER TABLE user_role ADD COLUMN IF NOT EXISTS createdBy UUID REFERENCES users(id);
ALTER TABLE user_role ADD COLUMN IF NOT EXISTS modifiedBy UUID REFERENCES users(id);
ALTER TABLE user_role ADD COLUMN IF NOT EXISTS createdOn TIMESTAMP;
ALTER TABLE user_role ADD COLUMN IF NOT EXISTS modifiedOn TIMESTAMP;

ALTER TABLE role ADD COLUMN IF NOT EXISTS createdBy UUID REFERENCES users(id);
ALTER TABLE role ADD COLUMN IF NOT EXISTS modifiedBy UUID REFERENCES users(id);
ALTER TABLE role ADD COLUMN IF NOT EXISTS createdOn TIMESTAMP;
ALTER TABLE role ADD COLUMN IF NOT EXISTS modifiedOn TIMESTAMP;

ALTER TABLE order_line_number ADD COLUMN IF NOT EXISTS createdBy UUID REFERENCES users(id);
ALTER TABLE order_line_number ADD COLUMN IF NOT EXISTS modifiedBy UUID REFERENCES users(id);
ALTER TABLE order_line_number ADD COLUMN IF NOT EXISTS createdOn TIMESTAMP;
ALTER TABLE order_line_number ADD COLUMN IF NOT EXISTS modifiedOn TIMESTAMP;
